name = "typing-testris"
main = "src/index.js"
compatibility_date = "2023-12-01"

# KV namespace for global leaderboard
[[kv_namespaces]]
binding = "LEADERBOARD_KV"
id = "aa766996999b4e368d80eaaf2b2e0a72"